server {
    listen 80;
    server_name 52.66.246.12;

    root /usr/share/nginx/html/login;               # index.html location
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Proxy API to backend node app at localhost:3000
    location /api/ {
        proxy_pass http://127.0.0.1:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

--------------------------------------------------------------------
server {
    listen 80;
    server_name _;

    # Frontend proxy to 5000 --> 80 
    location / {
        proxy_pass http://127.0.0.1:5000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Backend
    location /api/ {
        proxy_pass http://127.0.0.1:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
